# Changes here will be overwritten by Copier
_commit: v0.5.0
_src_path: git@github.com:zauberzeug/nicegui-template.git
dependency_management: uv
include_ai_instructions: true
module_name: feldfreund_devkit
project_description: A sturdy development platform for autonomous outdoor robotics
project_name: feldfreund_devkit
python_versions:
- '3.11'
- '3.12'
- '3.13'
- '3.14'
use_precommit: true
use_rosys: true
