from feldfreund_devkit.config import (
    BluetoothConfiguration,
    BumperConfiguration,
    CameraConfiguration,
    FeldfreundConfiguration,
    FlashlightConfiguration,
    GnssConfiguration,
    MjpegCameraConfig,
    RobotBrainConfiguration,
    TracksConfiguration,
    UsbCameraConfig,
)

config = FeldfreundConfiguration(
    robot_id='Example',
    bluetooth=BluetoothConfiguration(name='example', pin_code=123456),
    bumper=BumperConfiguration(pin_front_top=21, pin_front_bottom=35, pin_back=18),
    cameras=CameraConfiguration(
        main=UsbCameraConfig(camera_id='example-usb-0', width=1280, height=720, fps=10),
        front=MjpegCameraConfig(camera_id='example-mac-4', width=1280, height=720),
        back=MjpegCameraConfig(camera_id='example-mac-3', width=1280, height=720),
        right=MjpegCameraConfig(camera_id='example-mac-1', width=1280, height=720),
        left=MjpegCameraConfig(camera_id='example-mac-2', width=1280, height=720),
    ),
    flashlight=FlashlightConfiguration(),
    gnss=GnssConfiguration(),
    implement=None,
    imu=None,
    robot_brain=RobotBrainConfiguration(name='rbexample', nand=True),
    wheels=TracksConfiguration(is_left_reversed=True,
                               is_right_reversed=False,
                               left_back_can_address=0x000,
                               left_front_can_address=0x100,
                               right_back_can_address=0x200,
                               right_front_can_address=0x300,
                               odrive_version=6),
)
