name: Milestone Assigned

on:
  pull_request:
    types: [milestoned, demilestoned, opened]

jobs:
  check-milestone:
    # The export branch is written by a machine; its milestone is the one on the release that ships it.
    if: github.event.pull_request.head.ref != 'export'
    runs-on: ubuntu-latest

    steps:
      - name: Check for milestone
        run: |
          if [ -z "${{ github.event.pull_request.milestone }}" ]; then
            echo "No milestone assigned to the pull request."
            exit 1
          fi
